// <auto-generated />
using System;
using CBS_CC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CBS_CC.Migrations
{
    [DbContext(typeof(CBS_CCContext))]
    [Migration("20190831054923_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CBS_CC.Models.Estudiante", b =>
                {
                    b.Property<int>("EstudianteId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CarnetNo");

                    b.Property<string>("CodigoMINED");

                    b.Property<string>("Direccion")
                        .HasMaxLength(150);

                    b.Property<int>("Edad");

                    b.Property<string>("Estado")
                        .HasMaxLength(20);

                    b.Property<DateTime>("FechaNacimiento");

                    b.Property<string>("NombreCompleto")
                        .HasMaxLength(50);

                    b.Property<string>("Responsable")
                        .HasMaxLength(50);

                    b.Property<string>("Sexo")
                        .HasMaxLength(10);

                    b.Property<string>("Telefono")
                        .HasMaxLength(13);

                    b.HasKey("EstudianteId");

                    b.ToTable("Estudiante");
                });
#pragma warning restore 612, 618
        }
    }
}
